config/routes.rb
UserbinBoilerplate::Application.routes.draw do

  get 'account' => 'account#index'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  before_filter :authenticate_user!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Rails &hearts; Userbin</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.2/css/bootstrap.min.css" media="all" rel="stylesheet" type="text/css" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
  </head>
  <style>
    .jumbotron {
      background-color: #fff;
    }
    .jumbotron .btn {
      font-size: 21px;
      padding: 14px 24px;
    }
    .dashboard {
      padding: 40px 15px;
      text-align: center;
    }
  </style>
  <body>

    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Rails &hearts; Userbin</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if Userbin.user_logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= Userbin.current_user.email %> <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'My Account', account_path %></li>
                  <li><a href="/" class="ub-logout">Log out</a></li>
                </ul>
              </li>
            <% else %>
              <li><a href="/account" class="ub-login">Log in</a></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <%= yield %>

  </body>
</html>

app/views/welcome/index.html.erb
<div class="container">
  <div class="jumbotron text-center">
    <h1>Rails &hearts; Userbin</h1>
    <p class="lead">Yay, you've just launched a site where your users authenticates through Userbin.</p>
    <% if Userbin.config.app_id.to_i > 0 %>
      <p class="lead">We've added the class <code>ub-signup</code> to the button below and <code>ub-login</code> to the navbar. Now sign up to your new site and enter the protected area.</p>
      <p><a class="btn btn-lg btn-success ub-signup" href="#" role="button">Sign up now</a></p>
    <% else %>
      <p class="lead">
        Right now Userbin is running in demo mode.
        <br>
        Configure this app with your own app ID and secret:
      </p>
      <pre class="well text-left col-sm-6 col-sm-offset-3">
  # ./config/initializers/userbin.rb
  Userbin.configure do |config|
    config.app_id = "YOUR_APP_ID"
    config.api_secret = "YOUR_API_SECRET"
  end
      </pre>
    <% end %>
  </div>
</div>